spring:
  application:
    name: java-crm
    key: ${JWT_KEY}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_crm
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    name: java_crm
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
app:
  security:
    recovery:
      cooldown: PT1M
      ttl: PT15M